Rigs of Rods Multiplayer Server: Messaging Class Reference
Messaging Class Reference
#include <messaging.h>
Public Member Functions
Messaging (void)
~Messaging (void)
Static Public Member Functions
static int sendmessage (SWInetSocket *socket, int type, unsigned int source, unsigned int len, char *content)
static int receivemessage (SWInetSocket *socket, int *type, unsigned int *source, unsigned int *wrotelen, char *content, unsigned int bufferlen)
Detailed Description
Definition at line 38 of file messaging.h.
Constructor & Destructor Documentation
Messaging::Messaging (void) [inline]
Definition at line 41 of file messaging.h.
{;}
Messaging::~Messaging (void) [inline]
Definition at line 42 of file messaging.h.
{;}
Member Function Documentation
int Messaging::sendmessage (SWInetSocket * socket, int type, unsigned int source, unsigned int len, char * content) [static]
Parameters:
socket socket to communicate over
type a type... dunno
source who is sending the message
len length of the content being sent
content message to send
Returns:
dunno
Definition at line 30 of file messaging.cpp.
References header_t::command, header_t::size, and header_t::source.
Referenced by Sequencer::createClient(), Listener::threadstart(), and Broadcaster::threadstart().
{
        SWBaseSocket::SWBaseError error;
        header_t head;
        head.command=type;
        head.source=source;
        head.size=len;
        unsigned int hlen=0;
        while (hlen<sizeof(header_t))
        {
                int sendnum=socket->send(((char*)&head)+hlen, sizeof(header_t)-hlen, &error);
                if (sendnum<0 || error!=SWBaseSocket::ok)
                {
                        return -1;
                }
                hlen+=sendnum;
        }
        if (len>0)
        {
                int rlen=0;
                while (rlen<(int)head.size)
                {
                        int sendnum=socket->send(content+rlen, head.size-rlen, &error);
                        if (sendnum<0 || error!=SWBaseSocket::ok)
{
                                return -1;
                        }
                        rlen+=sendnum;
                }
        }
        return 0;
}
int Messaging::receivemessage (SWInetSocket * socket, int * type, unsigned int * source, unsigned int * wrotelen, char * content, unsigned int bufferlen) [static]
Name: receivemessage
Parameters:
*socket,:
*type,:
*source,:
*wrotelen,:
content,:
bufferlen,:
Returns:
Definition at line 76 of file messaging.cpp.
References header_t::command, header_t::size, and header_t::source.
Referenced by Receiver::threadstart(), and Listener::threadstart().
{
        SWBaseSocket::SWBaseError error;
        header_t head;
        unsigned int hlen=0;
        while (hlen<sizeof(header_t))
        {
                int recvnum=socket->recv(((char*)&head)+hlen, sizeof(header_t)-hlen,&error);
                if (recvnum<=0 || error!=SWBaseSocket::ok)
                {
                        return -1;
                }
                hlen+=recvnum;
        }
        if (head.size<=bufferlen)
        {
                int rlen=0;
                while (rlen<(int)head.size)
                {
                        int recvnum=socket->recv(content+rlen, head.size-rlen, &error);
                        if (recvnum<=0 || error!=SWBaseSocket::ok)
{
                                *wrotelen=rlen;
                                return -1;
                        }
                        rlen+=recvnum;
                }
        } else return -2;
        *type=head.command;
        *source=head.source;
        *wrotelen=head.size;
        return 0;
}
The documentation for this class was generated from the following files:
messaging.h
messaging.cpp