rorserver: Notifier Class Reference
Notifier Class Reference
#include <notifier.h>
Public Member Functions
Notifier (char *pubip, int port, Sequencer *seq, int max_client, char *servname, char *terrname, bool pwprotected, int servermode)
~Notifier (void)
void loop ()
int HTTPGET (char *URL)
int HTTPPOST (char *URL, char *data)
char * getResponse ()
bool unregisterServer ()
call to the master server to unregister this server.
Private Member Functions
bool registerServer ()
registration call to the master server to register this server
bool sendHearbeat ()
Private Attributes
int lport
int maxclient
char * public_ip
char * server_name
char * terrain_name
Sequencer * sequencer
char httpresp [65536]
char challenge [256]
bool exit
bool passprotected
bool wasregistered
int servermode
int error_count
Detailed Description
notifier class handles communications with the master server
Definition at line 29 of file notifier.h.
Constructor & Destructor Documentation
Notifier::Notifier (char * pubip, int port, Sequencer * seq, int max_client, char * servname, char * terrname, bool pwprotected, int servermode)
Definition at line 26 of file notifier.cpp.
References error_count, lport, maxclient, passprotected, public_ip, sequencer, server_name, servermode, terrain_name, and wasregistered.
Notifier::~Notifier (void)
Definition at line 40 of file notifier.cpp.
References exit.
Member Function Documentation
bool Notifier::registerServer () [private]
registration call to the master server to register this server
Definition at line 48 of file notifier.cpp.
References challenge, HTTPGET(), httpresp, lport, maxclient, passprotected, public_ip, REPO_URLPREFIX, RORNET_VERSION, server_name, terrain_name, and wasregistered.
Referenced by loop().
bool Notifier::sendHearbeat () [private]
Definition at line 90 of file notifier.cpp.
References challenge, Sequencer::getHeartbeatData(), HTTPPOST(), httpresp, REPO_URLPREFIX, and sequencer.
Referenced by loop().
void Notifier::loop ()
Definition at line 107 of file notifier.cpp.
References error_count, exit, LOG_ERROR, LOG_WARN, logmsgf(), registerServer(), sendHearbeat(), SERVER_AUTO, SERVER_INET, servermode, and unregisterServer().
Referenced by Sequencer::notifyRoutine().
int Notifier::HTTPGET (char * URL)
Definition at line 154 of file notifier.cpp.
References httpresp, LOG_ERROR, logmsgf(), and REPO_SERVER.
Referenced by registerServer(), and unregisterServer().
int Notifier::HTTPPOST (char * URL, char * data)
Definition at line 193 of file notifier.cpp.
References httpresp, LOG_DEBUG, LOG_ERROR, logmsgf(), and REPO_SERVER.
Referenced by sendHearbeat().
char* Notifier::getResponse () [inline]
Definition at line 57 of file notifier.h.
References httpresp.
bool Notifier::unregisterServer ()
call to the master server to unregister this server.
Definition at line 75 of file notifier.cpp.
References challenge, HTTPGET(), httpresp, REPO_URLPREFIX, and wasregistered.
Referenced by handler(), and loop().
Member Data Documentation
int Notifier::lport [private]
Definition at line 32 of file notifier.h.
Referenced by Notifier(), and registerServer().
int Notifier::maxclient [private]
Definition at line 33 of file notifier.h.
Referenced by Notifier(), and registerServer().
char* Notifier::public_ip [private]
Definition at line 34 of file notifier.h.
Referenced by Notifier(), and registerServer().
char* Notifier::server_name [private]
Definition at line 35 of file notifier.h.
Referenced by Notifier(), and registerServer().
char* Notifier::terrain_name [private]
Definition at line 36 of file notifier.h.
Referenced by Notifier(), and registerServer().
Sequencer* Notifier::sequencer [private]
Definition at line 37 of file notifier.h.
Referenced by Notifier(), and sendHearbeat().
char Notifier::httpresp[65536] [private]
Definition at line 38 of file notifier.h.
Referenced by getResponse(), HTTPGET(), HTTPPOST(), registerServer(), sendHearbeat(), and unregisterServer().
char Notifier::challenge[256] [private]
Definition at line 39 of file notifier.h.
Referenced by registerServer(), sendHearbeat(), and unregisterServer().
bool Notifier::exit [private]
Definition at line 40 of file notifier.h.
Referenced by loop(), and ~Notifier().
bool Notifier::passprotected [private]
Definition at line 41 of file notifier.h.
Referenced by Notifier(), and registerServer().
bool Notifier::wasregistered [private]
Definition at line 42 of file notifier.h.
Referenced by Notifier(), registerServer(), and unregisterServer().
int Notifier::servermode [private]
Definition at line 43 of file notifier.h.
Referenced by loop(), and Notifier().
int Notifier::error_count [private]
Definition at line 44 of file notifier.h.
Referenced by loop(), and Notifier().
The documentation for this class was generated from the following files:
dev/workspace/rorserver/notifier.h
dev/workspace/rorserver/notifier.cpp