Rigs of Rods Multiplayer Server: Sequencer Class Reference
Sequencer Class Reference
#include <sequencer.h>
Public Member Functions
Sequencer (char *pubip, int listenport, char *servname, char *terrname, int max_clients, int servermode, char *password)
~Sequencer (void)
void createClient (SWInetSocket *sock, char *name)
initilize client information
void killerthreadstart ()
call to start the thread to disconnect clients from the server.
void disconnect (int pos, char *error)
call to initiate the disconnect processes for a client.
void queueMessage (int pos, int type, char *data, unsigned int len)
void enableFlow (int id)
void notifyRoutine ()
void notifyAllVehicles (int id)
int getNumClients ()
returns the number of clients connected to this server
int getHeartbeatData (char *challenge, char *hearbeatdata)
void printStats ()
prints the Stats view, of who is connected and what slot they are in
Public Attributes
Notifier * notifier
Private Attributes
pthread_t killerthread
pthread_cond_t killer_cv
pthread_mutex_t killer_mutex
mutex used for locking access to the killqueue
pthread_mutex_t clients_mutex
mutex used for locking access to the clients array
Listener * listener
client_t * clients
clients is a list of all the available client connections, it is allocated
int maxclients
maximum number of clients allowed to connect to the server.
unsigned int fuid
int killqueue [256]
killqueue is a queue of clients to be killed. killqueue is a queue of clients to be removed from the server. it is an array of integers, where each integer is a position in the client list.
int freekillqueue
freekillqueue holds the number of spots available in the killqueue
int servermode
Detailed Description
Definition at line 60 of file sequencer.h.
Constructor & Destructor Documentation
Sequencer::Sequencer (char * pubip, int listenport, char * servname, char * terrname, int max_clients, int servermode, char * password)
Definition at line 32 of file sequencer.cpp.
References client_t::broadcaster, clients, clients_mutex, FREE, freekillqueue, fuid, killer_cv, killer_mutex, killerthread, listener, maxclients, notifier, client_t::receiver, s_klthreadstart(), SERVER_AUTO, SERVER_INET, servermode, and client_t::status.
{
        pthread_mutex_init(&killer_mutex, NULL);
        pthread_cond_init(&killer_cv, NULL);
        pthread_mutex_init(&clients_mutex, NULL);
        freekillqueue=0;
        servermode=smode;
        pthread_create(&killerthread, NULL, s_klthreadstart, this);
        fuid=1;
        notifier=0;
        maxclients=max_clients;
        clients=(client_t*)malloc(sizeof(client_t)*maxclients);
        for (int i=0; i<maxclients; i++)
        {
                clients[i].status=FREE;
                clients[i].broadcaster=new Broadcaster(this);
                clients[i].receiver=new Receiver(this);
        }
        listener=new Listener(listenport, this);
        bool pwprotected = false;
        if(pass && strnlen(pass,250)>0)
                pwprotected = true;
        if(servermode == SERVER_INET || servermode == SERVER_AUTO)
                notifier=new Notifier(pubip, listenport, this, max_clients, servname, terrname, pwprotected, servermode);
}
Sequencer::~Sequencer (void)
Definition at line 62 of file sequencer.cpp.
References clients, listener, LOG_DEBUG, logmsgf(), maxclients, and notifier.
{
        for (int i=0; i<maxclients && &clients[i]; i++)
        {
                logmsgf(LOG_DEBUG,"clients[%d]", i);
                if(clients[i].broadcaster){
                        logmsgf(LOG_DEBUG,"delete clients[%d].broadcaster", i);
                        delete clients[i].broadcaster;
                } else {
                        logmsgf(LOG_DEBUG,"clients[%d].broadcaster is null", i);
                }
                if(clients[i].receiver) {
                        logmsgf(LOG_DEBUG,"delete clients[%d].receiver", i);
                        delete clients[i].receiver;
                } else {
                        logmsgf(LOG_DEBUG,"clients[%d].receiver is null", i);
                }
        }
        if(notifier) delete notifier;
        delete listener;
        free(clients);
}
Member Function Documentation
void Sequencer::createClient (SWInetSocket * sock, char * name)
initilize client information
Definition at line 93 of file sequencer.cpp.
References client_t::broadcaster, clients, clients_mutex, client_t::flow, FREE, fuid, LOG_DEBUG, logmsgf(), maxclients, MSG2_FULL, MSG2_WELCOME, client_t::position, printStats(), client_t::receiver, Broadcaster::reset(), Receiver::reset(), Messaging::sendmessage(), client_t::sock, client_t::status, client_t::uid, USED, and client_t::vehicle_name.
Referenced by Listener::threadstart().
{
        //we have a confirmed client that wants to play
        //try to find a place for him
        pthread_mutex_lock(&clients_mutex);
        int pos=0;
        for (pos=0; pos<maxclients; pos++) if (clients[pos].status==FREE) break;
        if (pos==maxclients)
        {
                pthread_mutex_unlock(&clients_mutex);
                Messaging::sendmessage(sock, MSG2_FULL, 0, 0, 0);
                sock->disconnect();
                return;
        }
        //okay, create the stuff
        clients[pos].flow=false;
        clients[pos].status=USED;
        clients[pos].vehicle_name[0]=0;
        clients[pos].position=Vector3(0,0,0);
        strncpy(clients[pos].nickname, name, 21);
        clients[pos].uid=fuid;
        fuid++;
        clients[pos].sock=sock;
        clients[pos].receiver->reset(pos, sock); //this won't interlock
        clients[pos].broadcaster->reset(pos, sock); //this won't interlock
        pthread_mutex_unlock(&clients_mutex);
        Messaging::sendmessage(sock, MSG2_WELCOME, clients[pos].uid, 0, 0);
        logmsgf(LOG_DEBUG,"Sequencer: New client created in slot %i", pos);
        printStats();
}
void Sequencer::killerthreadstart ()
call to start the thread to disconnect clients from the server.
Definition at line 162 of file sequencer.cpp.
References client_t::broadcaster, BUSY, clients, clients_mutex, FREE, freekillqueue, killer_cv, killer_mutex, killqueue, LOG_DEBUG, logmsgf(), maxclients, MSG2_DELETE, Broadcaster::queueMessage(), client_t::receiver, client_t::sock, client_t::status, Broadcaster::stop(), Receiver::stop(), and USED.
{
        logmsgf(LOG_DEBUG,"Killer thread ready");
        while (1)
        {
                SWBaseSocket::SWBaseError error;
                logmsgf(LOG_DEBUG,"Killer entering cycle");
                pthread_mutex_lock(&killer_mutex);
                while (freekillqueue==0)
                        pthread_cond_wait(&killer_cv, &killer_mutex);
                //pop the kill queue
                int pos=killqueue[0];
                freekillqueue--;
                memcpy(killqueue, &killqueue[1], sizeof(int)*freekillqueue);
                pthread_mutex_unlock(&killer_mutex);
                logmsgf(LOG_DEBUG,"Killer called to kill %i", pos);
                pthread_mutex_lock(&clients_mutex); //this won't interlock unless
                                                                                        //disconnect is called from a clients_mutex owning thread
                logmsgf(LOG_DEBUG,"Killer got clients lock");
                if (clients[pos].status==USED)
                {
                        clients[pos].status=BUSY;
                        logmsgf(LOG_DEBUG,"Killer notifying");
                        //notify the others
                        for (int i=0; i<maxclients; i++)
{
                                if (clients[i].status==USED && strlen(clients[i].vehicle_name)>0)
{
                                        clients[i].broadcaster->queueMessage(clients[pos].uid, MSG2_DELETE, 0, 0);
                                }
                        }
                        logmsgf(LOG_DEBUG,"Killer done notifying");
                        //we release the mutex now
                        pthread_mutex_unlock(&clients_mutex);
                        //things are less critical, we can take time to cleanup properly and synchronously
                        logmsgf(LOG_DEBUG,"Killer force disconnect");
                        clients[pos].sock->disconnect(&error);
                        logmsgf(LOG_DEBUG,"Killer stopping receiver");
                        clients[pos].receiver->stop();
                        logmsgf(LOG_DEBUG,"Killer stopping broadcaster");
                        clients[pos].broadcaster->stop();
                        logmsgf(LOG_DEBUG,"Killer deleting socket");
                        delete clients[pos].sock;
                        pthread_mutex_lock(&clients_mutex);
                        logmsgf(LOG_DEBUG,"Killer got second clients lock");
                        clients[pos].status=FREE;
                }
                pthread_mutex_unlock(&clients_mutex);
                logmsgf(LOG_DEBUG,"Killer has properly killed %i", pos);
        }
}
void Sequencer::disconnect (int pos, char * error)
call to initiate the disconnect processes for a client.
Definition at line 218 of file sequencer.cpp.
References freekillqueue, killer_cv, killer_mutex, killqueue, LOG_DEBUG, and logmsgf().
Referenced by Receiver::threadstart(), and Broadcaster::threadstart().
{
        //this routine is a potential trouble maker as it can be called from many thread contexts
        //so we use a killer thread
        logmsgf(LOG_DEBUG,"ERROR Disconnecting Slot %d: %s", pos, errormsg);
        pthread_mutex_lock(&killer_mutex);
        //first check if not already queued
        bool found=false;
        for (int i=0; i<freekillqueue; i++) if (killqueue[i]==pos) {found=true; break;};
        if (!found)
        {
                killqueue[freekillqueue]=pos;
                freekillqueue++;
                pthread_cond_signal(&killer_cv);
        }
        pthread_mutex_unlock(&killer_mutex);
}
void Sequencer::queueMessage (int pos, int type, char * data, unsigned int len)
Definition at line 262 of file sequencer.cpp.
References client_t::broadcaster, clients, clients_mutex, LOG_DEBUG, logmsgf(), maxclients, MSG2_FORCE, MSG2_USE_VEHICLE, MSG2_VEHICLE_DATA, client_t::position, Broadcaster::queueMessage(), and USED.
Referenced by Receiver::threadstart().
{
        pthread_mutex_lock(&clients_mutex);
        if (type==MSG2_USE_VEHICLE)
        {
                data[len]=0;
                strncpy(clients[pos].vehicle_name, data, 129);
                logmsgf(LOG_DEBUG,"On the fly vehicle registration for slot %d: %s", pos, clients[pos].vehicle_name);
                //printStats();
                //we alter the message to add user info
                strcpy(data+len+1, clients[pos].nickname);
                len+=(int)strlen(clients[pos].nickname)+2;
        }
        if (type==MSG2_VEHICLE_DATA)
        {
                float* fpt=(float*)(data+sizeof(oob_t));
                clients[pos].position=Vector3(fpt[0], fpt[1], fpt[2]);
        }
        if (type==MSG2_FORCE)
        {
                //this message is to be sent to only one destination
                unsigned int destuid=((netforce_t*)data)->target_uid;
                for (int i=0; i<maxclients; i++)
                {
                        if (clients[i].status==USED && clients[i].flow && clients[i].uid==destuid)
                                clients[i].broadcaster->queueMessage(clients[pos].uid, type, data, len);
                }
        }
        else
        {
                //just push to all the present clients
                for (int i=0; i<maxclients; i++)
                {
                        if (clients[i].status==USED && clients[i].flow && i!=pos)
                                clients[i].broadcaster->queueMessage(clients[pos].uid, type, data, len);
#ifdef REFLECT_DEBUG
                        if (clients[i].status==USED && i==pos)
                                clients[i].broadcaster->queueMessage(clients[pos].uid+100, type, data, len);
#endif
                }
        }
        pthread_mutex_unlock(&clients_mutex);
}
void Sequencer::enableFlow (int id)
Definition at line 237 of file sequencer.cpp.
References clients, clients_mutex, and client_t::flow.
Referenced by Receiver::threadstart().
{
        pthread_mutex_lock(&clients_mutex);
        clients[pos].flow=true;
        pthread_mutex_unlock(&clients_mutex);
}
void Sequencer::notifyRoutine ()
Definition at line 86 of file sequencer.cpp.
References Notifier::loop(), and notifier.
Referenced by main().
{
        //we call the notify loop
        notifier->loop();
}
void Sequencer::notifyAllVehicles (int id)
Definition at line 245 of file sequencer.cpp.
References client_t::broadcaster, clients, clients_mutex, maxclients, MSG2_USE_VEHICLE, Broadcaster::queueMessage(), and USED.
Referenced by Receiver::threadstart().
{
        pthread_mutex_lock(&clients_mutex);
        for (int i=0; i<maxclients; i++)
        {
                if (i!=pos && clients[i].status==USED && strlen(clients[i].vehicle_name)>0)
                {
                        char message[512];
                        strcpy(message, clients[i].vehicle_name);
                        strcpy(message+strlen(clients[i].vehicle_name)+1, clients[i].nickname);
                        clients[pos].broadcaster->queueMessage(clients[i].uid, MSG2_USE_VEHICLE, message, (int)(strlen(clients[i].vehicle_name)+strlen(clients[i].nickname))+2);
                }
        }
        pthread_mutex_unlock(&clients_mutex);
}
int Sequencer::getNumClients ()
returns the number of clients connected to this server
Definition at line 153 of file sequencer.cpp.
References clients, clients_mutex, FREE, and maxclients.
{
        int count=0;
        pthread_mutex_lock(&clients_mutex);
        for (int i=0; i<maxclients; i++) if (clients[i].status!=FREE) count++;
        pthread_mutex_unlock(&clients_mutex);
        return count;
}
int Sequencer::getHeartbeatData (char * challenge, char * hearbeatdata)
Definition at line 126 of file sequencer.cpp.
References clients, clients_mutex, FREE, maxclients, client_t::position, and Vector3::toString().
Referenced by Notifier::sendHearbeat().
{
        pthread_mutex_lock(&clients_mutex);
        int clientnum =0;
        for (int i=0; i<maxclients; i++) if (clients[i].status!=FREE) clientnum++;
        sprintf(hearbeatdata, "%s\n" \
                              "version1\n" \
                              "%i\n", challenge, clientnum);
        if(clientnum > 0)
        {
                for (int i=0; i<maxclients; i++)
                {
                        if (clients[i].status != FREE)
{
                                char playerdata[1024] = "";
                                char positiondata[128] = "";
                                clients[i].position.toString(positiondata);
                                sprintf(playerdata, "%d;%s;%s;%s\n", i, clients[i].vehicle_name, clients[i].nickname, positiondata);
                                strcat(hearbeatdata, playerdata);
                        }
                }
        }
        pthread_mutex_unlock(&clients_mutex);
        return 0;
}
void Sequencer::printStats ()
prints the Stats view, of who is connected and what slot they are in
Definition at line 306 of file sequencer.cpp.
References BUSY, clients, clients_mutex, FREE, maxclients, client_t::nickname, and client_t::vehicle_name.
Referenced by createClient().
{
        SWBaseSocket::SWBaseError error;
        printf("Server occupancy:\n");
        printf("Slot Status   UID IP              Nickname, Vehicle\n");
        printf("--------------------------------------------------\n");
        pthread_mutex_lock(&clients_mutex);
        for (int i=0; i<maxclients; i++)
        {
                printf("%4i", i);
                if (clients[i].status==FREE) printf(" Free\n");
                else if (clients[i].status==BUSY)
                        printf(" Busy %5i %-16s %s, %s\n", clients[i].uid, "-", clients[i].nickname, clients[i].vehicle_name);
                else
                        printf(" Used %5i %-16s %s, %s\n", clients[i].uid, clients[i].sock->get_peerAddr(&error).c_str(), clients[i].nickname, clients[i].vehicle_name);
        }
        pthread_mutex_unlock(&clients_mutex);
}
Member Data Documentation
pthread_t Sequencer::killerthread [private]
Definition at line 63 of file sequencer.h.
Referenced by Sequencer().
pthread_cond_t Sequencer::killer_cv [private]
Definition at line 64 of file sequencer.h.
Referenced by disconnect(), killerthreadstart(), and Sequencer().
pthread_mutex_t Sequencer::killer_mutex [private]
mutex used for locking access to the killqueue
Definition at line 66 of file sequencer.h.
Referenced by disconnect(), killerthreadstart(), and Sequencer().
pthread_mutex_t Sequencer::clients_mutex [private]
mutex used for locking access to the clients array
Definition at line 68 of file sequencer.h.
Referenced by createClient(), enableFlow(), getHeartbeatData(), getNumClients(), killerthreadstart(), notifyAllVehicles(), printStats(), queueMessage(), and Sequencer().
Listener* Sequencer::listener [private]
Definition at line 70 of file sequencer.h.
Referenced by Sequencer(), and ~Sequencer().
client_t* Sequencer::clients [private]
clients is a list of all the available client connections, it is allocated
Definition at line 74 of file sequencer.h.
Referenced by createClient(), enableFlow(), getHeartbeatData(), getNumClients(), killerthreadstart(), notifyAllVehicles(), printStats(), queueMessage(), Sequencer(), and ~Sequencer().
int Sequencer::maxclients [private]
maximum number of clients allowed to connect to the server.
Definition at line 76 of file sequencer.h.
Referenced by createClient(), getHeartbeatData(), getNumClients(), killerthreadstart(), notifyAllVehicles(), printStats(), queueMessage(), Sequencer(), and ~Sequencer().
unsigned int Sequencer::fuid [private]
Definition at line 77 of file sequencer.h.
Referenced by createClient(), and Sequencer().
int Sequencer::killqueue[256] [private]
killqueue is a queue of clients to be killed. killqueue is a queue of clients to be removed from the server. it is an array of integers, where each integer is a position in the client list.
Definition at line 84 of file sequencer.h.
Referenced by disconnect(), and killerthreadstart().
int Sequencer::freekillqueue [private]
freekillqueue holds the number of spots available in the killqueue
Definition at line 88 of file sequencer.h.
Referenced by disconnect(), killerthreadstart(), and Sequencer().
int Sequencer::servermode [private]
Definition at line 89 of file sequencer.h.
Referenced by Sequencer().
Notifier* Sequencer::notifier
Definition at line 109 of file sequencer.h.
Referenced by handler(), notifyRoutine(), Sequencer(), and ~Sequencer().
The documentation for this class was generated from the following files:
sequencer.h
sequencer.cpp