Rigs of Rods Multiplayer Server: Receiver Class Reference
Receiver Class Reference
#include <receiver.h>
Public Member Functions
Receiver (Sequencer *seq)
~Receiver (void)
void reset (int pos, SWInetSocket *socky)
void stop ()
void threadstart ()
Private Attributes
pthread_t thread
Sequencer * sequencer
int id
SWInetSocket * sock
char dbuffer [MAX_MESSAGE_LENGTH]
bool alive
Detailed Description
Definition at line 27 of file receiver.h.
Constructor & Destructor Documentation
Receiver::Receiver (Sequencer * seq)
Definition at line 28 of file receiver.cpp.
References alive, sequencer, and sock.
{
        sequencer=seq;
        id=0;
        sock=0;
        alive=false;
}
Receiver::~Receiver (void)
Definition at line 36 of file receiver.cpp.
References stop().
{
        stop();
}
Member Function Documentation
void Receiver::reset (int pos, SWInetSocket * socky)
Definition at line 41 of file receiver.cpp.
References alive, LOG_ERROR, logmsgf(), s_lithreadstart(), sock, and thread.
Referenced by Sequencer::createClient().
{
        if (alive)
        {
                logmsgf(LOG_ERROR,"Whoa, receiver is still alive!");
                return;
        }
        id=pos;
        sock=socky;
        alive=true;
        //start a listener thread
        pthread_create(&thread, NULL, s_lithreadstart, this);
}
void Receiver::stop ()
Definition at line 55 of file receiver.cpp.
References alive.
Referenced by Sequencer::killerthreadstart(), and ~Receiver().
{
        //pthread_cancel(thread);
        //pthread_join(thread, NULL);
        alive=false;
}
void Receiver::threadstart ()
Definition at line 62 of file receiver.cpp.
References dbuffer, Sequencer::disconnect(), Sequencer::enableFlow(), LOG_DEBUG, logmsgf(), MAX_MESSAGE_LENGTH, MSG2_BUFFER_SIZE, MSG2_CHAT, MSG2_FORCE, MSG2_USE_VEHICLE, MSG2_VEHICLE_DATA, Sequencer::notifyAllVehicles(), Sequencer::queueMessage(), Messaging::receivemessage(), sequencer, and sock.
{
        logmsgf(LOG_DEBUG,"Receive thread %d started", id);
        //get the vehicle description
        int type;
        unsigned int source;
        unsigned int len;
        //security fix: we limit the size of the vehicle name to 128 characters <- from Luigi Auriemma
        if (Messaging::receivemessage(sock, &type, &source, &len, dbuffer, 128)) {
                sequencer->disconnect(id, "Messaging abuse 1");
                pthread_exit(NULL);
        }
        if (type!=MSG2_USE_VEHICLE) {
                sequencer->disconnect(id, "Protocol error 1");
                pthread_exit(NULL);
        }
        //security
        dbuffer[len]=0;
        //we queue the use vehicle message for others
        sequencer->queueMessage(id, type, dbuffer, len);
        //get the buffer size, not really usefull but a good way to detect errors
        if (Messaging::receivemessage(sock, &type, &source, &len, dbuffer, 4)) {
                sequencer->disconnect(id, "Messaging abuse 2");
                pthread_exit(NULL);
        }
        if (type!=MSG2_BUFFER_SIZE) {
                sequencer->disconnect(id, "Protocol error 2");
                pthread_exit(NULL);
        }
        unsigned int buffersize=*((unsigned int*)dbuffer);
        if (buffersize>MAX_MESSAGE_LENGTH) {
                sequencer->disconnect(id, "Memory error from client");
                pthread_exit(NULL);
        }
        //notify the client of all pre-existing vehicles
        sequencer->notifyAllVehicles(id);
        //okay, we are ready, we can receive data frames
        sequencer->enableFlow(id);
        logmsgf(LOG_DEBUG,"Slot %d is switching to FLOW", id);
        while (1)
        {
                if (Messaging::receivemessage(sock, &type, &source, &len, dbuffer, MAX_MESSAGE_LENGTH)) {
                        sequencer->disconnect(id, "Game connection closed");
                        pthread_exit(NULL);
                }
                if (type!=MSG2_VEHICLE_DATA && type!=MSG2_CHAT && type!=MSG2_FORCE) {
                        sequencer->disconnect(id, "Protocol error 3");
                        pthread_exit(NULL);
                }
                sequencer->queueMessage(id, type, dbuffer, len);
        }
        pthread_exit(NULL);
}
Member Data Documentation
pthread_t Receiver::thread [private]
Definition at line 30 of file receiver.h.
Referenced by reset().
Sequencer* Receiver::sequencer [private]
Definition at line 31 of file receiver.h.
Referenced by Receiver(), and threadstart().
int Receiver::id [private]
Definition at line 32 of file receiver.h.
SWInetSocket* Receiver::sock [private]
Definition at line 33 of file receiver.h.
Referenced by Receiver(), reset(), and threadstart().
char Receiver::dbuffer[MAX_MESSAGE_LENGTH] [private]
Definition at line 34 of file receiver.h.
Referenced by threadstart().
bool Receiver::alive [private]
Definition at line 35 of file receiver.h.
Referenced by Receiver(), reset(), and stop().
The documentation for this class was generated from the following files:
receiver.h
receiver.cpp