Rigs of Rods Multiplayer Server: CSimpleOptTempl< SOCHAR > Class Template Reference
CSimpleOptTempl< SOCHAR > Class Template Reference
Implementation of the SimpleOpt class.
#include <SimpleOpt.h>
Public Member Functions
CSimpleOptTempl ()
Initialize the class. Init() must be called later.
CSimpleOptTempl (int argc, SOCHAR *argv[], const SOption *a_rgOptions, int a_nFlags=0)
Initialize the class in preparation for use.
void Init (int a_argc, SOCHAR *a_argv[], const SOption *a_rgOptions, int a_nFlags=0)
Initialize the class in preparation for calling Next.
void SetOptions (const SOption *a_rgOptions)
Change the current options table during option parsing.
void SetFlags (int a_nFlags)
Change the current flags during option parsing.
bool HasFlag (int a_nFlag) const
Query if a particular flag is set.
bool Next ()
Advance to the next option if available.
ESOError LastError () const
Return the last error that occurred.
int OptionId () const
Return the nId value from the options array for the current option.
SOCHAR * OptionText () const
Return the pszArg from the options array for the current option.
SOCHAR * OptionArg () const
Return the argument for the current option where one exists.
SOCHAR ** MultiArg (int n)
Validate and return the desired number of arguments.
int FileCount () const
Returned the number of entries in the Files() array.
SOCHAR * File (int n) const
Return the specified file argument.
SOCHAR ** Files () const
Return the array of files.
Private Member Functions
SOCHAR PrepareArg (SOCHAR *a_pszString) const
bool NextClumped ()
void ShuffleArg (int a_nStartIdx, int a_nCount)
int LookupOption (const SOCHAR *a_pszOption) const
int CalcMatch (const SOCHAR *a_pszSource, const SOCHAR *a_pszTest) const
SOCHAR * FindEquals (SOCHAR *s) const
Private Attributes
const SOption * m_rgOptions
int m_nFlags
int m_nOptionIdx
int m_nOptionId
int m_nNextOption
int m_nLastArg
int m_argc
SOCHAR ** m_argv
SOCHAR * m_pszOptionText
SOCHAR * m_pszOptionArg
SOCHAR * m_pszClump
SOCHAR m_szShort [3]
ESOError m_nLastError
Classes
struct SOption
Structure used to define all known options.
Detailed Description
template<class SOCHAR>
class CSimpleOptTempl< SOCHAR >
Implementation of the SimpleOpt class.
Definition at line 249 of file SimpleOpt.h.
Constructor & Destructor Documentation
template<class SOCHAR> CSimpleOptTempl< SOCHAR >::CSimpleOptTempl () [inline]
Initialize the class. Init() must be called later.
Definition at line 262 of file SimpleOpt.h.
References CSimpleOptTempl< SOCHAR >::Init().
{ Init(0, NULL, NULL, 0); }
template<class SOCHAR> CSimpleOptTempl< SOCHAR >::CSimpleOptTempl (int argc, SOCHAR * argv[], const SOption * a_rgOptions, int a_nFlags = 0) [inline]
Initialize the class in preparation for use.
Definition at line 265 of file SimpleOpt.h.
References CSimpleOptTempl< SOCHAR >::Init().
{
                Init(argc, argv, a_rgOptions, a_nFlags);
        }
Member Function Documentation
template<class SOCHAR> void CSimpleOptTempl< SOCHAR >::Init (int a_argc, SOCHAR * a_argv[], const SOption * a_rgOptions, int a_nFlags = 0) [inline]
Initialize the class in preparation for calling Next.
The table of options pointed to by a_rgOptions does not need to be valid at the time that Init() is called. However on every call to Next() the table pointed to must be a valid options table with the last valid entry set to SO_END_OF_OPTIONS.
NOTE: the array pointed to by a_argv will be modified by this class and must not be used or modified outside of member calls to this class.
Parameters:
a_argc Argument array size
a_argv Argument array
a_rgOptions Valid option array
a_nFlags Optional flags to modify the processing of the arguments
Definition at line 417 of file SimpleOpt.h.
References CSimpleOptTempl< SOCHAR >::m_argc, CSimpleOptTempl< SOCHAR >::m_argv, CSimpleOptTempl< SOCHAR >::m_nFlags, CSimpleOptTempl< SOCHAR >::m_nLastArg, CSimpleOptTempl< SOCHAR >::m_nLastError, CSimpleOptTempl< SOCHAR >::m_nNextOption, CSimpleOptTempl< SOCHAR >::m_nOptionId, CSimpleOptTempl< SOCHAR >::m_nOptionIdx, CSimpleOptTempl< SOCHAR >::m_pszClump, CSimpleOptTempl< SOCHAR >::m_pszOptionArg, CSimpleOptTempl< SOCHAR >::m_pszOptionText, CSimpleOptTempl< SOCHAR >::m_rgOptions, CSimpleOptTempl< SOCHAR >::m_szShort, SO_O_USEALL, and SO_SUCCESS.
Referenced by CSimpleOptTempl< SOCHAR >::CSimpleOptTempl().
{
        m_argc           = a_argc;
        m_nLastArg       = a_argc;
        m_argv           = a_argv;
        m_rgOptions      = a_rgOptions;
        m_nLastError     = SO_SUCCESS;
        m_nOptionIdx     = 0;
        m_nOptionId      = -1;
        m_pszOptionText  = NULL;
        m_pszOptionArg   = NULL;
        m_nNextOption    = (a_nFlags & SO_O_USEALL) ? 0 : 1;
        m_szShort[0]     = (SOCHAR)'-';
        m_szShort[2]     = (SOCHAR)'\0';
        m_nFlags         = a_nFlags;
        m_pszClump       = NULL;
}
template<class SOCHAR> void CSimpleOptTempl< SOCHAR >::SetOptions (const SOption * a_rgOptions) [inline]
Change the current options table during option parsing.
Parameters:
a_rgOptions Valid option array
Definition at line 291 of file SimpleOpt.h.
References CSimpleOptTempl< SOCHAR >::m_rgOptions.
{ m_rgOptions = a_rgOptions; }
template<class SOCHAR> void CSimpleOptTempl< SOCHAR >::SetFlags (int a_nFlags) [inline]
Change the current flags during option parsing.
Note that changing the SO_O_USEALL flag here will have no affect. It must be set using Init() or the constructor.
Parameters:
a_nFlags Flags to modify the processing of the arguments
Definition at line 300 of file SimpleOpt.h.
References CSimpleOptTempl< SOCHAR >::m_nFlags.
{ m_nFlags = a_nFlags; }
template<class SOCHAR> bool CSimpleOptTempl< SOCHAR >::HasFlag (int a_nFlag) const [inline]
Query if a particular flag is set.
Definition at line 303 of file SimpleOpt.h.
References CSimpleOptTempl< SOCHAR >::m_nFlags.
Referenced by CSimpleOptTempl< SOCHAR >::LookupOption(), CSimpleOptTempl< SOCHAR >::MultiArg(), CSimpleOptTempl< SOCHAR >::Next(), and CSimpleOptTempl< SOCHAR >::PrepareArg().
{ return (m_nFlags & a_nFlag) == a_nFlag; }
template<class SOCHAR> bool CSimpleOptTempl< SOCHAR >::Next () [inline]
Advance to the next option if available.
When all options have been processed it will return false. When true has been returned, you must check for an invalid or unrecognized option using the LastError() method. This will be return an error value other than SO_SUCCESS on an error. All standard data (e.g. OptionText(), OptionArg(), OptionId(), etc) will be available depending on the error.
After all options have been processed, the remaining files from the command line can be processed in same order as they were passed to the program.
Returns:
true option or error available for processing
false all options have been processed
Definition at line 442 of file SimpleOpt.h.
References CSimpleOptTempl< SOCHAR >::FindEquals(), CSimpleOptTempl< SOCHAR >::HasFlag(), CSimpleOptTempl< SOCHAR >::LookupOption(), CSimpleOptTempl< SOCHAR >::m_argv, CSimpleOptTempl< SOCHAR >::m_nLastArg, CSimpleOptTempl< SOCHAR >::m_nLastError, CSimpleOptTempl< SOCHAR >::m_nNextOption, CSimpleOptTempl< SOCHAR >::m_nOptionId, CSimpleOptTempl< SOCHAR >::m_nOptionIdx, CSimpleOptTempl< SOCHAR >::m_pszClump, CSimpleOptTempl< SOCHAR >::m_pszOptionArg, CSimpleOptTempl< SOCHAR >::m_pszOptionText, CSimpleOptTempl< SOCHAR >::m_rgOptions, CSimpleOptTempl< SOCHAR >::m_szShort, CSimpleOptTempl< SOCHAR >::MultiArg(), CSimpleOptTempl< SOCHAR >::SOption::nArgType, CSimpleOptTempl< SOCHAR >::NextClumped(), CSimpleOptTempl< SOCHAR >::SOption::nId, CSimpleOptTempl< SOCHAR >::PrepareArg(), CSimpleOptTempl< SOCHAR >::SOption::pszArg, CSimpleOptTempl< SOCHAR >::ShuffleArg(), SO_ARG_INVALID, SO_ARG_INVALID_TYPE, SO_ARG_MISSING, SO_ASSERT, SO_MULTI, SO_NONE, SO_O_CLUMP, SO_O_NOERR, SO_O_PEDANTIC, SO_O_SHORTARG, SO_OPT, SO_REQ_CMB, SO_REQ_SEP, and SO_SUCCESS.
{
        // process a clumped option string if appropriate
        if (m_pszClump && *m_pszClump) {
                // silently discard invalid clumped option
                bool bIsValid = NextClumped();
                while (*m_pszClump && !bIsValid && HasFlag(SO_O_NOERR)) {
                        bIsValid = NextClumped();
                }
                // return this option if valid or we are returning errors
                if (bIsValid || !HasFlag(SO_O_NOERR)) {
                        return true;
                }
        }
        SO_ASSERT(!m_pszClump || !*m_pszClump);
        m_pszClump = NULL;
        // init for the next option
        m_nOptionIdx    = m_nNextOption;
        m_nOptionId     = -1;
        m_pszOptionText = NULL;
        m_pszOptionArg  = NULL;
        m_nLastError    = SO_SUCCESS;
        // find the next option
        SOCHAR cFirst;
        int nTableIdx = -1;
        int nOptIdx = m_nOptionIdx;
        while (nTableIdx < 0 && nOptIdx < m_nLastArg) {
                // assumed argument
                m_pszOptionText = m_argv[nOptIdx];
                m_pszOptionArg  = NULL;
                // find this option in the options table
                cFirst = PrepareArg(m_pszOptionText);
                if (m_pszOptionText[0] == (SOCHAR)'-') {
                        // find any combined argument string and remove equals sign
                        m_pszOptionArg = FindEquals(m_pszOptionText);
                        if (m_pszOptionArg) {
                                *m_pszOptionArg++ = (SOCHAR)'\0';
                        }
                }
                nTableIdx = LookupOption(m_pszOptionText);
                // if we didn't find this option but if it is a short form
                // option then we try the alternative forms
                if (nTableIdx < 0
                        && !m_pszOptionArg
                        && m_pszOptionText[0] == (SOCHAR)'-'
                        && m_pszOptionText[1]
                && m_pszOptionText[1] != (SOCHAR)'-'
                        && m_pszOptionText[2])
                {
                        // test for a short-form with argument if appropriate
                        if (HasFlag(SO_O_SHORTARG)) {
                                m_szShort[1] = m_pszOptionText[1];
                                int nIdx = LookupOption(m_szShort);
                                if (nIdx >= 0
                                        && (m_rgOptions[nIdx].nArgType == SO_REQ_CMB
                                        || m_rgOptions[nIdx].nArgType == SO_OPT))
{
                                        m_pszOptionArg  = &m_pszOptionText[2];
                                        m_pszOptionText = m_szShort;
                                        nTableIdx       = nIdx;
                                }
                        }
                        // test for a clumped short-form option string and we didn't
                        // match on the short-form argument above
                        if (nTableIdx < 0 && HasFlag(SO_O_CLUMP))  {
                                m_pszClump = &m_pszOptionText[1];
                                ++m_nNextOption;
                                if (nOptIdx > m_nOptionIdx) {
                                        ShuffleArg(m_nOptionIdx, nOptIdx - m_nOptionIdx);
                                }
                                return Next();
                        }
                }
                // The option wasn't found. If it starts with a switch character
                // and we are not suppressing errors for invalid options then it
                // is reported as an error, otherwise it is data.
                if (nTableIdx < 0) {
                        if (!HasFlag(SO_O_NOERR) && m_pszOptionText[0] == (SOCHAR)'-') {
                                break;
                        }
                        m_pszOptionText[0] = cFirst;
                        ++nOptIdx;
                        if (m_pszOptionArg) {
                                *(--m_pszOptionArg) = (SOCHAR)'=';
                        }
                }
        }
        // end of options
        if (nOptIdx >= m_nLastArg) {
                if (nOptIdx > m_nOptionIdx) {
                        ShuffleArg(m_nOptionIdx, nOptIdx - m_nOptionIdx);
                }
                return false;
        }
        ++m_nNextOption;
        // get the option id
        ESOArgType nArgType = SO_NONE;
        if (nTableIdx < 0) {
                m_nLastError = (ESOError) nTableIdx; // error code
        }
        else {
                m_nOptionId     = m_rgOptions[nTableIdx].nId;
                m_pszOptionText = m_rgOptions[nTableIdx].pszArg;
                // ensure that the arg type is valid
                nArgType = m_rgOptions[nTableIdx].nArgType;
                switch (nArgType) {
case SO_NONE:
        if (m_pszOptionArg) {
                m_nLastError = SO_ARG_INVALID;
        }
        break;
case SO_REQ_SEP:
        if (m_pszOptionArg) {
                // they wanted separate args, but we got a combined one, unless
                // we are being pedantic about things, just accept it.
                if (HasFlag(SO_O_PEDANTIC)) {
                        m_nLastError = SO_ARG_INVALID_TYPE;
                }
        }
        // more processing after we shuffle
        break;
case SO_REQ_CMB:
        if (!m_pszOptionArg) {
                m_nLastError = SO_ARG_MISSING;
        }
        break;
case SO_OPT:
        // nothing to do
        break;
case SO_MULTI:
        // nothing to do. Caller must now check for valid arguments
        // using GetMultiArg()
        break;
                }
        }
        // shuffle the files out of the way
        if (nOptIdx > m_nOptionIdx) {
                ShuffleArg(m_nOptionIdx, nOptIdx - m_nOptionIdx);
        }
        // we need to return the separate arg if required, just re-use the
        // multi-arg code because it all does the same thing
        if (nArgType == SO_REQ_SEP && !m_pszOptionArg && m_nLastError == SO_SUCCESS) {
                SOCHAR ** ppArgs = MultiArg(1);
                if (ppArgs) {
                        m_pszOptionArg = *ppArgs;
                }
        }
        return true;
}
template<class SOCHAR> ESOError CSimpleOptTempl< SOCHAR >::LastError () const [inline]
Return the last error that occurred.
This function must always be called before processing the current option. This function is available only when Next() has returned true.
Definition at line 327 of file SimpleOpt.h.
References CSimpleOptTempl< SOCHAR >::m_nLastError.
{ return m_nLastError; }
template<class SOCHAR> int CSimpleOptTempl< SOCHAR >::OptionId () const [inline]
Return the nId value from the options array for the current option.
This function is available only when Next() has returned true.
Definition at line 333 of file SimpleOpt.h.
References CSimpleOptTempl< SOCHAR >::m_nOptionId.
{ return m_nOptionId; }
template<class SOCHAR> SOCHAR* CSimpleOptTempl< SOCHAR >::OptionText () const [inline]
Return the pszArg from the options array for the current option.
This function is available only when Next() has returned true.
Definition at line 339 of file SimpleOpt.h.
References CSimpleOptTempl< SOCHAR >::m_pszOptionText.
{ return m_pszOptionText; }
template<class SOCHAR> SOCHAR* CSimpleOptTempl< SOCHAR >::OptionArg () const [inline]
Return the argument for the current option where one exists.
If there is no argument for the option, this will return NULL. This function is available only when Next() has returned true.
Definition at line 346 of file SimpleOpt.h.
References CSimpleOptTempl< SOCHAR >::m_pszOptionArg.
{ return m_pszOptionArg; }
template<class SOCHAR> SOCHAR ** CSimpleOptTempl< SOCHAR >::MultiArg (int n) [inline]
Validate and return the desired number of arguments.
This is only valid when OptionId() has return the ID of an option that is registered as SO_MULTI. It may be called multiple times each time returning the desired number of arguments. Previously returned argument pointers are remain valid.
If an error occurs during processing, NULL will be returned and the error will be available via LastError().
Parameters:
n Number of arguments to return.
Definition at line 807 of file SimpleOpt.h.
References CSimpleOptTempl< SOCHAR >::HasFlag(), CSimpleOptTempl< SOCHAR >::m_argv, CSimpleOptTempl< SOCHAR >::m_nLastArg, CSimpleOptTempl< SOCHAR >::m_nLastError, CSimpleOptTempl< SOCHAR >::m_nNextOption, CSimpleOptTempl< SOCHAR >::PrepareArg(), SO_ARG_INVALID_DATA, SO_ARG_MISSING, and SO_O_NOERR.
Referenced by CSimpleOptTempl< SOCHAR >::Next().
{
        // ensure we have enough arguments
        if (m_nNextOption + a_nCount > m_nLastArg) {
                m_nLastError = SO_ARG_MISSING;
                return NULL;
        }
        // our argument array
        SOCHAR ** rgpszArg = &m_argv[m_nNextOption];
        // Ensure that each of the following don't start with an switch character.
        // Only make this check if we are returning errors for unknown arguments.
        if (!HasFlag(SO_O_NOERR)) {
                for (int n = 0; n < a_nCount; ++n) {
                        SOCHAR ch = PrepareArg(rgpszArg[n]);
                        if (rgpszArg[n][0] == (SOCHAR)'-') {
                                rgpszArg[n][0] = ch;
                                m_nLastError = SO_ARG_INVALID_DATA;
                                return NULL;
                        }
                        rgpszArg[n][0] = ch;
                }
        }
        // all good
        m_nNextOption += a_nCount;
        return rgpszArg;
}
template<class SOCHAR> int CSimpleOptTempl< SOCHAR >::FileCount () const [inline]
Returned the number of entries in the Files() array.
After Next() has returned false, this will be the list of files (or otherwise unprocessed arguments).
Definition at line 367 of file SimpleOpt.h.
References CSimpleOptTempl< SOCHAR >::m_argc, and CSimpleOptTempl< SOCHAR >::m_nLastArg.
Referenced by CSimpleOptTempl< SOCHAR >::File().
{ return m_argc - m_nLastArg; }
template<class SOCHAR> SOCHAR* CSimpleOptTempl< SOCHAR >::File (int n) const [inline]
Return the specified file argument.
Parameters:
n Index of the file to return. This must be between 0 and FileCount() - 1;
Definition at line 374 of file SimpleOpt.h.
References CSimpleOptTempl< SOCHAR >::FileCount(), CSimpleOptTempl< SOCHAR >::m_argv, CSimpleOptTempl< SOCHAR >::m_nLastArg, and SO_ASSERT.
{
                SO_ASSERT(n >= 0 && n < FileCount());
                return m_argv[m_nLastArg + n];
        }
template<class SOCHAR> SOCHAR** CSimpleOptTempl< SOCHAR >::Files () const [inline]
Return the array of files.
Definition at line 380 of file SimpleOpt.h.
References CSimpleOptTempl< SOCHAR >::m_argv, and CSimpleOptTempl< SOCHAR >::m_nLastArg.
{ return &m_argv[m_nLastArg]; }
template<class SOCHAR> SOCHAR CSimpleOptTempl< SOCHAR >::PrepareArg (SOCHAR * a_pszString) const [inline, private]
Definition at line 611 of file SimpleOpt.h.
References CSimpleOptTempl< SOCHAR >::HasFlag(), and SO_O_NOSLASH.
Referenced by CSimpleOptTempl< SOCHAR >::MultiArg(), and CSimpleOptTempl< SOCHAR >::Next().
{
#ifdef _WIN32
        // On Windows we can accept the forward slash as a single character
        // option delimiter, but it cannot replace the '-' option used to
        // denote stdin. On Un*x paths may start with slash so it may not
        // be used to start an option.
        if (!HasFlag(SO_O_NOSLASH)
                && a_pszString[0] == (SOCHAR)'/'
                && a_pszString[1]
        && a_pszString[1] != (SOCHAR)'-')
        {
                a_pszString[0] = (SOCHAR)'-';
                return (SOCHAR)'/';
        }
#endif
        return a_pszString[0];
}
template<class SOCHAR> bool CSimpleOptTempl< SOCHAR >::NextClumped () [inline, private]
Definition at line 634 of file SimpleOpt.h.
References CSimpleOptTempl< SOCHAR >::LookupOption(), CSimpleOptTempl< SOCHAR >::m_nFlags, CSimpleOptTempl< SOCHAR >::m_nLastError, CSimpleOptTempl< SOCHAR >::m_nOptionId, CSimpleOptTempl< SOCHAR >::m_pszClump, CSimpleOptTempl< SOCHAR >::m_pszOptionArg, CSimpleOptTempl< SOCHAR >::m_pszOptionText, CSimpleOptTempl< SOCHAR >::m_rgOptions, CSimpleOptTempl< SOCHAR >::m_szShort, CSimpleOptTempl< SOCHAR >::SOption::nArgType, CSimpleOptTempl< SOCHAR >::SOption::nId, SO_ARG_MISSING, SO_NONE, SO_O_EXACT, SO_REQ_CMB, and SO_SUCCESS.
Referenced by CSimpleOptTempl< SOCHAR >::Next().
{
        // prepare for the next clumped option
        m_szShort[1]    = *m_pszClump++;
        m_nOptionId     = -1;
        m_pszOptionText = m_szShort;
        m_pszOptionArg  = NULL;
        m_nLastError    = SO_SUCCESS;
        // lookup this option, ensure that we are using exact matching
        int nSavedFlags = m_nFlags;
        m_nFlags = SO_O_EXACT;
        int nTableIdx = LookupOption(m_pszOptionText);
        m_nFlags = nSavedFlags;
        // unknown option
        if (nTableIdx < 0) {
                m_nLastError = (ESOError) nTableIdx; // error code
                return false;
        }
        // valid option
        ESOArgType nArgType = m_rgOptions[nTableIdx].nArgType;
        if (nArgType == SO_NONE) {
                m_nOptionId = m_rgOptions[nTableIdx].nId;
                return true;
        }
        if (nArgType == SO_REQ_CMB && *m_pszClump) {
                m_nOptionId = m_rgOptions[nTableIdx].nId;
                m_pszOptionArg = m_pszClump;
                while (*m_pszClump) ++m_pszClump; // must point to an empty string
                return true;
        }
        // invalid option as it requires an argument
        m_nLastError = SO_ARG_MISSING;
        return true;
}
template<class SOCHAR> void CSimpleOptTempl< SOCHAR >::ShuffleArg (int a_nStartIdx, int a_nCount) [inline, private]
Definition at line 684 of file SimpleOpt.h.
References CSimpleOptTempl< SOCHAR >::m_argc, CSimpleOptTempl< SOCHAR >::m_argv, and CSimpleOptTempl< SOCHAR >::m_nLastArg.
Referenced by CSimpleOptTempl< SOCHAR >::Next().
{
        SOCHAR * buf[200];
        int n, nSrc, nDst;
        int nTail = m_argc - a_nStartIdx - a_nCount;
        // make a copy of the elements to be moved
        nSrc = a_nStartIdx;
        nDst = 0;
        while (nDst < a_nCount) {
                buf[nDst++] = m_argv[nSrc++];
        }
        // move the tail down
        nSrc = a_nStartIdx + a_nCount;
        nDst = a_nStartIdx;
        for (n = 0; n < nTail; ++n) {
                m_argv[nDst++] = m_argv[nSrc++];
        }
        // append the moved elements to the tail
        nSrc = 0;
        nDst = a_nStartIdx + nTail;
        for (n = 0; n < a_nCount; ++n) {
                m_argv[nDst++] = buf[nSrc++];
        }
        // update the index of the last unshuffled arg
        m_nLastArg -= a_nCount;
}
template<class SOCHAR> int CSimpleOptTempl< SOCHAR >::LookupOption (const SOCHAR * a_pszOption) const [inline, private]
Definition at line 722 of file SimpleOpt.h.
References CSimpleOptTempl< SOCHAR >::CalcMatch(), CSimpleOptTempl< SOCHAR >::HasFlag(), CSimpleOptTempl< SOCHAR >::m_rgOptions, CSimpleOptTempl< SOCHAR >::SOption::nId, SO_ASSERT, SO_O_EXACT, SO_OPT_INVALID, and SO_OPT_MULTIPLE.
Referenced by CSimpleOptTempl< SOCHAR >::Next(), and CSimpleOptTempl< SOCHAR >::NextClumped().
{
        int nBestMatch = -1;    // index of best match so far
        int nBestMatchLen = 0;  // matching characters of best match
        int nLastMatchLen = 0;  // matching characters of last best match
        for (int n = 0; m_rgOptions[n].nId >= 0; ++n) {
                // the option table must use hyphens as the option character,
                // the slash character is converted to a hyphen for testing.
                SO_ASSERT(m_rgOptions[n].pszArg[0] != (SOCHAR)'/');
                int nMatchLen = CalcMatch(m_rgOptions[n].pszArg, a_pszOption);
                if (nMatchLen == -1) {
                        return n;
                }
                if (nMatchLen > 0 && nMatchLen >= nBestMatchLen) {
                        nLastMatchLen = nBestMatchLen;
                        nBestMatchLen = nMatchLen;
                        nBestMatch = n;
                }
        }
        // only partial matches or no match gets to here, ensure that we
        // don't return a partial match unless it is a clear winner
        if (HasFlag(SO_O_EXACT) || nBestMatch == -1) {
                return SO_OPT_INVALID;
        }
        return (nBestMatchLen > nLastMatchLen) ? nBestMatch : SO_OPT_MULTIPLE;
}
template<class SOCHAR> int CSimpleOptTempl< SOCHAR >::CalcMatch (const SOCHAR * a_pszSource, const SOCHAR * a_pszTest) const [inline, private]
Definition at line 758 of file SimpleOpt.h.
Referenced by CSimpleOptTempl< SOCHAR >::LookupOption().
{
        if (!a_pszSource || !a_pszTest) {
                return 0;
        }
        // match and skip leading hyphens
        while (*a_pszSource == (SOCHAR)'-' && *a_pszSource == *a_pszTest) {
                ++a_pszSource; ++a_pszTest;
        }
        if (*a_pszSource == (SOCHAR)'-' || *a_pszTest == (SOCHAR)'-') {
                return 0;
        }
        // find matching number of characters in the strings
        int nLen = 0;
        while (*a_pszSource && *a_pszSource == *a_pszTest) {
                ++a_pszSource; ++a_pszTest; ++nLen;
        }
        // if we have exhausted the source...
        if (!*a_pszSource) {
                // and the test strings, then it's a perfect match
                if (!*a_pszTest) {
                        return -1;
                }
                // otherwise the match failed as the test is longer than
                // the source. i.e. "--mant" will not match the option "--man".
                return 0;
        }
        // if we haven't exhausted the test string then it is not a match
        // i.e. "--mantle" will not best-fit match to "--mandate" at all.
        if (*a_pszTest) {
                return 0;
        }
        // partial match to the current length of the test string
        return nLen;
}
template<class SOCHAR> SOCHAR* CSimpleOptTempl< SOCHAR >::FindEquals (SOCHAR * s) const [inline, private]
Definition at line 390 of file SimpleOpt.h.
Referenced by CSimpleOptTempl< SOCHAR >::Next().
{
                while (*s && *s != (SOCHAR)'=') ++s;
                return *s ? s : NULL;
        }
Member Data Documentation
template<class SOCHAR> const SOption* CSimpleOptTempl< SOCHAR >::m_rgOptions [private]
Definition at line 396 of file SimpleOpt.h.
Referenced by CSimpleOptTempl< SOCHAR >::Init(), CSimpleOptTempl< SOCHAR >::LookupOption(), CSimpleOptTempl< SOCHAR >::Next(), CSimpleOptTempl< SOCHAR >::NextClumped(), and CSimpleOptTempl< SOCHAR >::SetOptions().
template<class SOCHAR> int CSimpleOptTempl< SOCHAR >::m_nFlags [private]
Definition at line 397 of file SimpleOpt.h.
Referenced by CSimpleOptTempl< SOCHAR >::HasFlag(), CSimpleOptTempl< SOCHAR >::Init(), CSimpleOptTempl< SOCHAR >::NextClumped(), and CSimpleOptTempl< SOCHAR >::SetFlags().
template<class SOCHAR> int CSimpleOptTempl< SOCHAR >::m_nOptionIdx [private]
Definition at line 398 of file SimpleOpt.h.
Referenced by CSimpleOptTempl< SOCHAR >::Init(), and CSimpleOptTempl< SOCHAR >::Next().
template<class SOCHAR> int CSimpleOptTempl< SOCHAR >::m_nOptionId [private]
Definition at line 399 of file SimpleOpt.h.
Referenced by CSimpleOptTempl< SOCHAR >::Init(), CSimpleOptTempl< SOCHAR >::Next(), CSimpleOptTempl< SOCHAR >::NextClumped(), and CSimpleOptTempl< SOCHAR >::OptionId().
template<class SOCHAR> int CSimpleOptTempl< SOCHAR >::m_nNextOption [private]
Definition at line 400 of file SimpleOpt.h.
Referenced by CSimpleOptTempl< SOCHAR >::Init(), CSimpleOptTempl< SOCHAR >::MultiArg(), and CSimpleOptTempl< SOCHAR >::Next().
template<class SOCHAR> int CSimpleOptTempl< SOCHAR >::m_nLastArg [private]
Definition at line 401 of file SimpleOpt.h.
Referenced by CSimpleOptTempl< SOCHAR >::File(), CSimpleOptTempl< SOCHAR >::FileCount(), CSimpleOptTempl< SOCHAR >::Files(), CSimpleOptTempl< SOCHAR >::Init(), CSimpleOptTempl< SOCHAR >::MultiArg(), CSimpleOptTempl< SOCHAR >::Next(), and CSimpleOptTempl< SOCHAR >::ShuffleArg().
template<class SOCHAR> int CSimpleOptTempl< SOCHAR >::m_argc [private]
Definition at line 402 of file SimpleOpt.h.
Referenced by CSimpleOptTempl< SOCHAR >::FileCount(), CSimpleOptTempl< SOCHAR >::Init(), and CSimpleOptTempl< SOCHAR >::ShuffleArg().
template<class SOCHAR> SOCHAR** CSimpleOptTempl< SOCHAR >::m_argv [private]
Definition at line 403 of file SimpleOpt.h.
Referenced by CSimpleOptTempl< SOCHAR >::File(), CSimpleOptTempl< SOCHAR >::Files(), CSimpleOptTempl< SOCHAR >::Init(), CSimpleOptTempl< SOCHAR >::MultiArg(), CSimpleOptTempl< SOCHAR >::Next(), and CSimpleOptTempl< SOCHAR >::ShuffleArg().
template<class SOCHAR> SOCHAR* CSimpleOptTempl< SOCHAR >::m_pszOptionText [private]
Definition at line 404 of file SimpleOpt.h.
Referenced by CSimpleOptTempl< SOCHAR >::Init(), CSimpleOptTempl< SOCHAR >::Next(), CSimpleOptTempl< SOCHAR >::NextClumped(), and CSimpleOptTempl< SOCHAR >::OptionText().
template<class SOCHAR> SOCHAR* CSimpleOptTempl< SOCHAR >::m_pszOptionArg [private]
Definition at line 405 of file SimpleOpt.h.
Referenced by CSimpleOptTempl< SOCHAR >::Init(), CSimpleOptTempl< SOCHAR >::Next(), CSimpleOptTempl< SOCHAR >::NextClumped(), and CSimpleOptTempl< SOCHAR >::OptionArg().
template<class SOCHAR> SOCHAR* CSimpleOptTempl< SOCHAR >::m_pszClump [private]
Definition at line 406 of file SimpleOpt.h.
Referenced by CSimpleOptTempl< SOCHAR >::Init(), CSimpleOptTempl< SOCHAR >::Next(), and CSimpleOptTempl< SOCHAR >::NextClumped().
template<class SOCHAR> SOCHAR CSimpleOptTempl< SOCHAR >::m_szShort[3] [private]
Definition at line 407 of file SimpleOpt.h.
Referenced by CSimpleOptTempl< SOCHAR >::Init(), CSimpleOptTempl< SOCHAR >::Next(), and CSimpleOptTempl< SOCHAR >::NextClumped().
template<class SOCHAR> ESOError CSimpleOptTempl< SOCHAR >::m_nLastError [private]
Definition at line 408 of file SimpleOpt.h.
Referenced by CSimpleOptTempl< SOCHAR >::Init(), CSimpleOptTempl< SOCHAR >::LastError(), CSimpleOptTempl< SOCHAR >::MultiArg(), CSimpleOptTempl< SOCHAR >::Next(), and CSimpleOptTempl< SOCHAR >::NextClumped().
The documentation for this class was generated from the following file:
SimpleOpt.h