Rigs of Rods Multiplayer Server: Listener Class Reference
Listener Class Reference
#include <listener.h>
Public Member Functions
Listener (int port, Sequencer *seq)
~Listener (void)
void threadstart ()
Private Attributes
pthread_t thread
int lport
Sequencer * sequencer
Detailed Description
Definition at line 29 of file listener.h.
Constructor & Destructor Documentation
Listener::Listener (int port, Sequencer * seq)
Definition at line 28 of file listener.cpp.
References lport, s_lsthreadstart(), sequencer, and thread.
{
        lport=port;
        sequencer=seq;
        //start a listener thread
        pthread_create(&thread, NULL, s_lsthreadstart, this);
}
Listener::~Listener (void)
Definition at line 36 of file listener.cpp.
{
}
Member Function Documentation
void Listener::threadstart ()
Definition at line 40 of file listener.cpp.
References Sequencer::createClient(), LOG_DEBUG, LOG_ERROR, LOG_WARN, logmsgf(), lport, MSG2_HELLO, MSG2_USER, MSG2_VERSION, Messaging::receivemessage(), RORNET_VERSION, Messaging::sendmessage(), and sequencer.
{
        logmsgf(LOG_DEBUG,"Listerer thread starting");
        //here we start
        SWInetSocket listSocket;
        SWBaseSocket::SWBaseError error;
        //manage the listening socket
        listSocket.bind(lport, &error);
        if (error!=SWBaseSocket::ok)
        {
                //this is an error!
                logmsgf(LOG_ERROR,"FATAL Listerer: %s", error.get_error().c_str());
                //there is nothing we can do here
                exit(1);
                return;
        }
        listSocket.listen();
        //await connections
        logmsgf(LOG_WARN,"Listener ready");
        while (1)
        {
                logmsgf(LOG_DEBUG,"Listener awaiting connections");
                SWInetSocket *ts=(SWInetSocket *)listSocket.accept(&error);
                logmsgf(LOG_DEBUG,"Listener got a new connection");
                if (error!=SWBaseSocket::ok)
                {
                        logmsgf(LOG_ERROR,"ERROR Listener: %s", error.get_error().c_str());
                        continue;
                }
                //receive a magic
                int type;
                unsigned int source;
                unsigned int len;
                char buffer[256];
                if (Messaging::receivemessage(ts, &type, &source, &len, buffer, 256))
                {
                        logmsgf(LOG_ERROR,"ERROR Listener: receiving first message");
                        ts->disconnect(&error);
                        delete ts;
                        continue;
                }
                if (type==MSG2_HELLO)
                {
                        logmsgf(LOG_DEBUG,"Listener sending version");
                        //send the version information back
                        if (Messaging::sendmessage(ts, MSG2_VERSION, 0, (int)strlen(RORNET_VERSION), RORNET_VERSION))
{
                                logmsgf(LOG_ERROR,"ERROR Listener: sending version");
                                ts->disconnect(&error);
                                delete ts;
                                continue;
                        }
                        if(!strncmp(buffer, RORNET_VERSION, strlen(RORNET_VERSION)))
{
                                //receive user name
                                if (Messaging::receivemessage(ts, &type, &source, &len, buffer, 256))
{
                                        logmsgf(LOG_ERROR,"ERROR Listener: receiving user name");
                                        ts->disconnect(&error);
                                        delete ts;
                                        continue;
                                }
                                if (type==MSG2_USER)
{
                                        //create a new client
                                        //correct a bit the client name (trucate, validate)
                                        if (len>20) len=20;
                                        buffer[len]=0;
                                        for (unsigned int i=0; i<len; i++) if (buffer[i]<32 || buffer[i]>127 || buffer[i]==';') buffer[i]='#';
                                        logmsgf(LOG_DEBUG,"Listener creating a new client (%s)", buffer);
                                        sequencer->createClient(ts, buffer);
                                }
                                else
{
                                        logmsgf(LOG_ERROR,"Warning Listener: no user name");
                                        ts->disconnect(&error);
                                        delete ts;
                                }
                        }
                        else
{
                                logmsgf(LOG_ERROR,"ERROR Listener: bad version");
                                ts->disconnect(&error);
                                delete ts;
                        }
                }
                else
                {
                        logmsgf(LOG_ERROR,"ERROR Listener: No Hello");
                        ts->disconnect(&error);
                        delete ts;
                }
        }
}
Member Data Documentation
pthread_t Listener::thread [private]
Definition at line 32 of file listener.h.
Referenced by Listener().
int Listener::lport [private]
Definition at line 33 of file listener.h.
Referenced by Listener(), and threadstart().
Sequencer* Listener::sequencer [private]
Definition at line 34 of file listener.h.
Referenced by Listener(), and threadstart().
The documentation for this class was generated from the following files:
listener.h
listener.cpp