rorserver: dev/workspace/rorserver/messaging.cpp File Reference
dev/workspace/rorserver/messaging.cpp File Reference
#include "messaging.h"
#include <stdarg.h>
Functions
void logmsgf (int level, const char *format,...)
Variables
int loglevel = 1
Function Documentation
void logmsgf (int level, const char * format, ...)
Definition at line 114 of file messaging.cpp.
Referenced by Sequencer::createClient(), Sequencer::disconnect(), handler(), Notifier::HTTPGET(), Notifier::HTTPPOST(), Sequencer::killerthreadstart(), Notifier::loop(), Sequencer::queueMessage(), Receiver::reset(), Broadcaster::reset(), Broadcaster::stop(), Receiver::threadstart(), Listener::threadstart(), Broadcaster::threadstart(), Broadcaster::~Broadcaster(), and Sequencer::~Sequencer().
Variable Documentation
int loglevel = 1
Definition at line 110 of file messaging.cpp.
Referenced by logmsgf(), and main().